
title: ECEN 740
author: 
  name: 
  email: santosh@tamu.edu

collections:
  navigation:
    output: true

baseurl: "" 

include:
  - docs
  - images

header_pages:
  - home.md

markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge


 
